// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/vstable.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_vstable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_vstable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dialect       string                 `protobuf:"bytes,2,opt,name=dialect,proto3" json:"dialect,omitempty"`
	Dsn           string                 `protobuf:"bytes,3,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_api_vstable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConnectRequest) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *ConnectRequest) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_api_vstable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_api_vstable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_api_vstable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{5}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        *structpb.ListValue    `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_api_vstable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{6}
}

func (x *QueryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() *structpb.ListValue {
	if x != nil {
		return x.Params
	}
	return nil
}

type FieldInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldInfo) Reset() {
	*x = FieldInfo{}
	mi := &file_api_vstable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldInfo) ProtoMessage() {}

func (x *FieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldInfo.ProtoReflect.Descriptor instead.
func (*FieldInfo) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{7}
}

func (x *FieldInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Rows          []*structpb.Struct     `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Fields        []*FieldInfo           `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_api_vstable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QueryResponse) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResponse) GetFields() []*FieldInfo {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ColumnDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	EnumValues          []string               `protobuf:"bytes,4,rep,name=enum_values,json=enumValues,proto3" json:"enum_values,omitempty"`
	Length              *int64                 `protobuf:"varint,5,opt,name=length,proto3,oneof" json:"length,omitempty"`
	Precision           *int64                 `protobuf:"varint,6,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	Scale               *int64                 `protobuf:"varint,7,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	Nullable            bool                   `protobuf:"varint,8,opt,name=nullable,proto3" json:"nullable,omitempty"`
	DefaultValue        *string                `protobuf:"bytes,9,opt,name=default_value,json=defaultValue,proto3,oneof" json:"default_value,omitempty"`
	IsDefaultExpression bool                   `protobuf:"varint,10,opt,name=is_default_expression,json=isDefaultExpression,proto3" json:"is_default_expression,omitempty"`
	IsPrimaryKey        bool                   `protobuf:"varint,11,opt,name=is_primary_key,json=isPrimaryKey,proto3" json:"is_primary_key,omitempty"`
	IsAutoIncrement     bool                   `protobuf:"varint,12,opt,name=is_auto_increment,json=isAutoIncrement,proto3" json:"is_auto_increment,omitempty"`
	IsIdentity          bool                   `protobuf:"varint,13,opt,name=is_identity,json=isIdentity,proto3" json:"is_identity,omitempty"`
	Comment             string                 `protobuf:"bytes,14,opt,name=comment,proto3" json:"comment,omitempty"`
	PkConstraintName    string                 `protobuf:"bytes,15,opt,name=pk_constraint_name,json=pkConstraintName,proto3" json:"pk_constraint_name,omitempty"`
	OriginalIndex       int32                  `protobuf:"varint,16,opt,name=original_index,json=originalIndex,proto3" json:"original_index,omitempty"`
	Original            *ColumnDefinition      `protobuf:"bytes,17,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ColumnDefinition) Reset() {
	*x = ColumnDefinition{}
	mi := &file_api_vstable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDefinition) ProtoMessage() {}

func (x *ColumnDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDefinition.ProtoReflect.Descriptor instead.
func (*ColumnDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{9}
}

func (x *ColumnDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ColumnDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnDefinition) GetEnumValues() []string {
	if x != nil {
		return x.EnumValues
	}
	return nil
}

func (x *ColumnDefinition) GetLength() int64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *ColumnDefinition) GetPrecision() int64 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *ColumnDefinition) GetScale() int64 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *ColumnDefinition) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *ColumnDefinition) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *ColumnDefinition) GetIsDefaultExpression() bool {
	if x != nil {
		return x.IsDefaultExpression
	}
	return false
}

func (x *ColumnDefinition) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *ColumnDefinition) GetIsAutoIncrement() bool {
	if x != nil {
		return x.IsAutoIncrement
	}
	return false
}

func (x *ColumnDefinition) GetIsIdentity() bool {
	if x != nil {
		return x.IsIdentity
	}
	return false
}

func (x *ColumnDefinition) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ColumnDefinition) GetPkConstraintName() string {
	if x != nil {
		return x.PkConstraintName
	}
	return ""
}

func (x *ColumnDefinition) GetOriginalIndex() int32 {
	if x != nil {
		return x.OriginalIndex
	}
	return 0
}

func (x *ColumnDefinition) GetOriginal() *ColumnDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type IndexDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	IsUnique      bool                   `protobuf:"varint,4,opt,name=is_unique,json=isUnique,proto3" json:"is_unique,omitempty"`
	Original      *IndexDefinition       `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDefinition) Reset() {
	*x = IndexDefinition{}
	mi := &file_api_vstable_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDefinition) ProtoMessage() {}

func (x *IndexDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDefinition.ProtoReflect.Descriptor instead.
func (*IndexDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{10}
}

func (x *IndexDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IndexDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexDefinition) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *IndexDefinition) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *IndexDefinition) GetOriginal() *IndexDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type ForeignKeyDefinition struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Columns           []string               `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
	ReferencedTable   string                 `protobuf:"bytes,4,opt,name=referenced_table,json=referencedTable,proto3" json:"referenced_table,omitempty"`
	ReferencedColumns []string               `protobuf:"bytes,5,rep,name=referenced_columns,json=referencedColumns,proto3" json:"referenced_columns,omitempty"`
	OnDelete          string                 `protobuf:"bytes,6,opt,name=on_delete,json=onDelete,proto3" json:"on_delete,omitempty"`
	OnUpdate          string                 `protobuf:"bytes,7,opt,name=on_update,json=onUpdate,proto3" json:"on_update,omitempty"`
	Original          *ForeignKeyDefinition  `protobuf:"bytes,8,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForeignKeyDefinition) Reset() {
	*x = ForeignKeyDefinition{}
	mi := &file_api_vstable_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignKeyDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignKeyDefinition) ProtoMessage() {}

func (x *ForeignKeyDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignKeyDefinition.ProtoReflect.Descriptor instead.
func (*ForeignKeyDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{11}
}

func (x *ForeignKeyDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForeignKeyDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForeignKeyDefinition) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ForeignKeyDefinition) GetReferencedTable() string {
	if x != nil {
		return x.ReferencedTable
	}
	return ""
}

func (x *ForeignKeyDefinition) GetReferencedColumns() []string {
	if x != nil {
		return x.ReferencedColumns
	}
	return nil
}

func (x *ForeignKeyDefinition) GetOnDelete() string {
	if x != nil {
		return x.OnDelete
	}
	return ""
}

func (x *ForeignKeyDefinition) GetOnUpdate() string {
	if x != nil {
		return x.OnUpdate
	}
	return ""
}

func (x *ForeignKeyDefinition) GetOriginal() *ForeignKeyDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type CheckConstraintDefinition struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Expression    string                     `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	Original      *CheckConstraintDefinition `protobuf:"bytes,4,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConstraintDefinition) Reset() {
	*x = CheckConstraintDefinition{}
	mi := &file_api_vstable_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConstraintDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConstraintDefinition) ProtoMessage() {}

func (x *CheckConstraintDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConstraintDefinition.ProtoReflect.Descriptor instead.
func (*CheckConstraintDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{12}
}

func (x *CheckConstraintDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckConstraintDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckConstraintDefinition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CheckConstraintDefinition) GetOriginal() *CheckConstraintDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type ViewDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition    string                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Original      *ViewDefinition        `protobuf:"bytes,4,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewDefinition) Reset() {
	*x = ViewDefinition{}
	mi := &file_api_vstable_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewDefinition) ProtoMessage() {}

func (x *ViewDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewDefinition.ProtoReflect.Descriptor instead.
func (*ViewDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{13}
}

func (x *ViewDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ViewDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ViewDefinition) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *ViewDefinition) GetOriginal() *ViewDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type TriggerDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Timing        string                 `protobuf:"bytes,3,opt,name=timing,proto3" json:"timing,omitempty"`
	Event         string                 `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	TableName     string                 `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Definition    string                 `protobuf:"bytes,6,opt,name=definition,proto3" json:"definition,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Original      *TriggerDefinition     `protobuf:"bytes,8,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDefinition) Reset() {
	*x = TriggerDefinition{}
	mi := &file_api_vstable_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDefinition) ProtoMessage() {}

func (x *TriggerDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDefinition.ProtoReflect.Descriptor instead.
func (*TriggerDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TriggerDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerDefinition) GetTiming() string {
	if x != nil {
		return x.Timing
	}
	return ""
}

func (x *TriggerDefinition) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TriggerDefinition) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TriggerDefinition) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *TriggerDefinition) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TriggerDefinition) GetOriginal() *TriggerDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type RoutineDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Definition    string                 `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	Original      *RoutineDefinition     `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutineDefinition) Reset() {
	*x = RoutineDefinition{}
	mi := &file_api_vstable_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutineDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineDefinition) ProtoMessage() {}

func (x *RoutineDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineDefinition.ProtoReflect.Descriptor instead.
func (*RoutineDefinition) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{15}
}

func (x *RoutineDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutineDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoutineDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoutineDefinition) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *RoutineDefinition) GetOriginal() *RoutineDefinition {
	if x != nil {
		return x.Original
	}
	return nil
}

type DatabaseConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Charset             string                 `protobuf:"bytes,1,opt,name=charset,proto3" json:"charset,omitempty"`
	Collation           string                 `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	Engine              string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	AutoIncrementOffset int32                  `protobuf:"varint,4,opt,name=auto_increment_offset,json=autoIncrementOffset,proto3" json:"auto_increment_offset,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DatabaseConfig) Reset() {
	*x = DatabaseConfig{}
	mi := &file_api_vstable_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseConfig) ProtoMessage() {}

func (x *DatabaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseConfig.ProtoReflect.Descriptor instead.
func (*DatabaseConfig) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{16}
}

func (x *DatabaseConfig) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *DatabaseConfig) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *DatabaseConfig) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *DatabaseConfig) GetAutoIncrementOffset() int32 {
	if x != nil {
		return x.AutoIncrementOffset
	}
	return 0
}

type DiffRequest struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	Dialect            string                       `protobuf:"bytes,1,opt,name=dialect,proto3" json:"dialect,omitempty"`
	Schema             string                       `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	TableName          string                       `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	OldTableName       string                       `protobuf:"bytes,4,opt,name=old_table_name,json=oldTableName,proto3" json:"old_table_name,omitempty"`
	Columns            []*ColumnDefinition          `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty"`
	Indexes            []*IndexDefinition           `protobuf:"bytes,6,rep,name=indexes,proto3" json:"indexes,omitempty"`
	DeletedColumns     []*ColumnDefinition          `protobuf:"bytes,7,rep,name=deleted_columns,json=deletedColumns,proto3" json:"deleted_columns,omitempty"`
	DeletedIndexes     []*IndexDefinition           `protobuf:"bytes,8,rep,name=deleted_indexes,json=deletedIndexes,proto3" json:"deleted_indexes,omitempty"`
	ForeignKeys        []*ForeignKeyDefinition      `protobuf:"bytes,9,rep,name=foreign_keys,json=foreignKeys,proto3" json:"foreign_keys,omitempty"`
	DeletedForeignKeys []*ForeignKeyDefinition      `protobuf:"bytes,10,rep,name=deleted_foreign_keys,json=deletedForeignKeys,proto3" json:"deleted_foreign_keys,omitempty"`
	CheckConstraints   []*CheckConstraintDefinition `protobuf:"bytes,11,rep,name=check_constraints,json=checkConstraints,proto3" json:"check_constraints,omitempty"`
	DeletedChecks      []*CheckConstraintDefinition `protobuf:"bytes,12,rep,name=deleted_checks,json=deletedChecks,proto3" json:"deleted_checks,omitempty"`
	Views              []*ViewDefinition            `protobuf:"bytes,13,rep,name=views,proto3" json:"views,omitempty"`
	DeletedViews       []*ViewDefinition            `protobuf:"bytes,14,rep,name=deleted_views,json=deletedViews,proto3" json:"deleted_views,omitempty"`
	Triggers           []*TriggerDefinition         `protobuf:"bytes,15,rep,name=triggers,proto3" json:"triggers,omitempty"`
	DeletedTriggers    []*TriggerDefinition         `protobuf:"bytes,16,rep,name=deleted_triggers,json=deletedTriggers,proto3" json:"deleted_triggers,omitempty"`
	Routines           []*RoutineDefinition         `protobuf:"bytes,17,rep,name=routines,proto3" json:"routines,omitempty"`
	DeletedRoutines    []*RoutineDefinition         `protobuf:"bytes,18,rep,name=deleted_routines,json=deletedRoutines,proto3" json:"deleted_routines,omitempty"`
	Config             *DatabaseConfig              `protobuf:"bytes,19,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	mi := &file_api_vstable_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{17}
}

func (x *DiffRequest) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *DiffRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *DiffRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DiffRequest) GetOldTableName() string {
	if x != nil {
		return x.OldTableName
	}
	return ""
}

func (x *DiffRequest) GetColumns() []*ColumnDefinition {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *DiffRequest) GetIndexes() []*IndexDefinition {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *DiffRequest) GetDeletedColumns() []*ColumnDefinition {
	if x != nil {
		return x.DeletedColumns
	}
	return nil
}

func (x *DiffRequest) GetDeletedIndexes() []*IndexDefinition {
	if x != nil {
		return x.DeletedIndexes
	}
	return nil
}

func (x *DiffRequest) GetForeignKeys() []*ForeignKeyDefinition {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *DiffRequest) GetDeletedForeignKeys() []*ForeignKeyDefinition {
	if x != nil {
		return x.DeletedForeignKeys
	}
	return nil
}

func (x *DiffRequest) GetCheckConstraints() []*CheckConstraintDefinition {
	if x != nil {
		return x.CheckConstraints
	}
	return nil
}

func (x *DiffRequest) GetDeletedChecks() []*CheckConstraintDefinition {
	if x != nil {
		return x.DeletedChecks
	}
	return nil
}

func (x *DiffRequest) GetViews() []*ViewDefinition {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *DiffRequest) GetDeletedViews() []*ViewDefinition {
	if x != nil {
		return x.DeletedViews
	}
	return nil
}

func (x *DiffRequest) GetTriggers() []*TriggerDefinition {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *DiffRequest) GetDeletedTriggers() []*TriggerDefinition {
	if x != nil {
		return x.DeletedTriggers
	}
	return nil
}

func (x *DiffRequest) GetRoutines() []*RoutineDefinition {
	if x != nil {
		return x.Routines
	}
	return nil
}

func (x *DiffRequest) GetDeletedRoutines() []*RoutineDefinition {
	if x != nil {
		return x.DeletedRoutines
	}
	return nil
}

func (x *DiffRequest) GetConfig() *DatabaseConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GenerateSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Sqls          []string               `protobuf:"bytes,2,rep,name=sqls,proto3" json:"sqls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSQLResponse) Reset() {
	*x = GenerateSQLResponse{}
	mi := &file_api_vstable_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSQLResponse) ProtoMessage() {}

func (x *GenerateSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vstable_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSQLResponse.ProtoReflect.Descriptor instead.
func (*GenerateSQLResponse) Descriptor() ([]byte, []int) {
	return file_api_vstable_proto_rawDescGZIP(), []int{18}
}

func (x *GenerateSQLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateSQLResponse) GetSqls() []string {
	if x != nil {
		return x.Sqls
	}
	return nil
}

var File_api_vstable_proto protoreflect.FileDescriptor

const file_api_vstable_proto_rawDesc = "" +
	"\n" +
	"\x11api/vstable.proto\x12\avstable\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\r\n" +
	"\vPingRequest\"&\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"L\n" +
	"\x0eConnectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\adialect\x18\x02 \x01(\tR\adialect\x12\x10\n" +
	"\x03dsn\x18\x03 \x01(\tR\x03dsn\"+\n" +
	"\x0fConnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11DisconnectRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\fQueryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x122\n" +
	"\x06params\x18\x03 \x01(\v2\x1a.google.protobuf.ListValueR\x06params\"3\n" +
	"\tFieldInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x82\x01\n" +
	"\rQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.google.protobuf.StructR\x04rows\x12*\n" +
	"\x06fields\x18\x03 \x03(\v2\x12.vstable.FieldInfoR\x06fields\"\x8e\x05\n" +
	"\x10ColumnDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\venum_values\x18\x04 \x03(\tR\n" +
	"enumValues\x12\x1b\n" +
	"\x06length\x18\x05 \x01(\x03H\x00R\x06length\x88\x01\x01\x12!\n" +
	"\tprecision\x18\x06 \x01(\x03H\x01R\tprecision\x88\x01\x01\x12\x19\n" +
	"\x05scale\x18\a \x01(\x03H\x02R\x05scale\x88\x01\x01\x12\x1a\n" +
	"\bnullable\x18\b \x01(\bR\bnullable\x12(\n" +
	"\rdefault_value\x18\t \x01(\tH\x03R\fdefaultValue\x88\x01\x01\x122\n" +
	"\x15is_default_expression\x18\n" +
	" \x01(\bR\x13isDefaultExpression\x12$\n" +
	"\x0eis_primary_key\x18\v \x01(\bR\fisPrimaryKey\x12*\n" +
	"\x11is_auto_increment\x18\f \x01(\bR\x0fisAutoIncrement\x12\x1f\n" +
	"\vis_identity\x18\r \x01(\bR\n" +
	"isIdentity\x12\x18\n" +
	"\acomment\x18\x0e \x01(\tR\acomment\x12,\n" +
	"\x12pk_constraint_name\x18\x0f \x01(\tR\x10pkConstraintName\x12%\n" +
	"\x0eoriginal_index\x18\x10 \x01(\x05R\roriginalIndex\x125\n" +
	"\boriginal\x18\x11 \x01(\v2\x19.vstable.ColumnDefinitionR\boriginalB\t\n" +
	"\a_lengthB\f\n" +
	"\n" +
	"_precisionB\b\n" +
	"\x06_scaleB\x10\n" +
	"\x0e_default_value\"\xa2\x01\n" +
	"\x0fIndexDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12\x1b\n" +
	"\tis_unique\x18\x04 \x01(\bR\bisUnique\x124\n" +
	"\boriginal\x18\x05 \x01(\v2\x18.vstable.IndexDefinitionR\boriginal\"\xa3\x02\n" +
	"\x14ForeignKeyDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acolumns\x18\x03 \x03(\tR\acolumns\x12)\n" +
	"\x10referenced_table\x18\x04 \x01(\tR\x0freferencedTable\x12-\n" +
	"\x12referenced_columns\x18\x05 \x03(\tR\x11referencedColumns\x12\x1b\n" +
	"\ton_delete\x18\x06 \x01(\tR\bonDelete\x12\x1b\n" +
	"\ton_update\x18\a \x01(\tR\bonUpdate\x129\n" +
	"\boriginal\x18\b \x01(\v2\x1d.vstable.ForeignKeyDefinitionR\boriginal\"\x9f\x01\n" +
	"\x19CheckConstraintDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"expression\x18\x03 \x01(\tR\n" +
	"expression\x12>\n" +
	"\boriginal\x18\x04 \x01(\v2\".vstable.CheckConstraintDefinitionR\boriginal\"\x89\x01\n" +
	"\x0eViewDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\tR\n" +
	"definition\x123\n" +
	"\boriginal\x18\x04 \x01(\v2\x17.vstable.ViewDefinitionR\boriginal\"\xf6\x01\n" +
	"\x11TriggerDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06timing\x18\x03 \x01(\tR\x06timing\x12\x14\n" +
	"\x05event\x18\x04 \x01(\tR\x05event\x12\x1d\n" +
	"\n" +
	"table_name\x18\x05 \x01(\tR\ttableName\x12\x1e\n" +
	"\n" +
	"definition\x18\x06 \x01(\tR\n" +
	"definition\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x126\n" +
	"\boriginal\x18\b \x01(\v2\x1a.vstable.TriggerDefinitionR\boriginal\"\xa3\x01\n" +
	"\x11RoutineDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"definition\x18\x04 \x01(\tR\n" +
	"definition\x126\n" +
	"\boriginal\x18\x05 \x01(\v2\x1a.vstable.RoutineDefinitionR\boriginal\"\x94\x01\n" +
	"\x0eDatabaseConfig\x12\x18\n" +
	"\acharset\x18\x01 \x01(\tR\acharset\x12\x1c\n" +
	"\tcollation\x18\x02 \x01(\tR\tcollation\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x122\n" +
	"\x15auto_increment_offset\x18\x04 \x01(\x05R\x13autoIncrementOffset\"\xbf\b\n" +
	"\vDiffRequest\x12\x18\n" +
	"\adialect\x18\x01 \x01(\tR\adialect\x12\x16\n" +
	"\x06schema\x18\x02 \x01(\tR\x06schema\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12$\n" +
	"\x0eold_table_name\x18\x04 \x01(\tR\foldTableName\x123\n" +
	"\acolumns\x18\x05 \x03(\v2\x19.vstable.ColumnDefinitionR\acolumns\x122\n" +
	"\aindexes\x18\x06 \x03(\v2\x18.vstable.IndexDefinitionR\aindexes\x12B\n" +
	"\x0fdeleted_columns\x18\a \x03(\v2\x19.vstable.ColumnDefinitionR\x0edeletedColumns\x12A\n" +
	"\x0fdeleted_indexes\x18\b \x03(\v2\x18.vstable.IndexDefinitionR\x0edeletedIndexes\x12@\n" +
	"\fforeign_keys\x18\t \x03(\v2\x1d.vstable.ForeignKeyDefinitionR\vforeignKeys\x12O\n" +
	"\x14deleted_foreign_keys\x18\n" +
	" \x03(\v2\x1d.vstable.ForeignKeyDefinitionR\x12deletedForeignKeys\x12O\n" +
	"\x11check_constraints\x18\v \x03(\v2\".vstable.CheckConstraintDefinitionR\x10checkConstraints\x12I\n" +
	"\x0edeleted_checks\x18\f \x03(\v2\".vstable.CheckConstraintDefinitionR\rdeletedChecks\x12-\n" +
	"\x05views\x18\r \x03(\v2\x17.vstable.ViewDefinitionR\x05views\x12<\n" +
	"\rdeleted_views\x18\x0e \x03(\v2\x17.vstable.ViewDefinitionR\fdeletedViews\x126\n" +
	"\btriggers\x18\x0f \x03(\v2\x1a.vstable.TriggerDefinitionR\btriggers\x12E\n" +
	"\x10deleted_triggers\x18\x10 \x03(\v2\x1a.vstable.TriggerDefinitionR\x0fdeletedTriggers\x126\n" +
	"\broutines\x18\x11 \x03(\v2\x1a.vstable.RoutineDefinitionR\broutines\x12E\n" +
	"\x10deleted_routines\x18\x12 \x03(\v2\x1a.vstable.RoutineDefinitionR\x0fdeletedRoutines\x12/\n" +
	"\x06config\x18\x13 \x01(\v2\x17.vstable.DatabaseConfigR\x06config\"C\n" +
	"\x13GenerateSQLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04sqls\x18\x02 \x03(\tR\x04sqls2\x98\x03\n" +
	"\rEngineService\x123\n" +
	"\x04Ping\x12\x14.vstable.PingRequest\x1a\x15.vstable.PingResponse\x12>\n" +
	"\tDbConnect\x12\x17.vstable.ConnectRequest\x1a\x18.vstable.ConnectResponse\x12E\n" +
	"\n" +
	"Disconnect\x12\x1a.vstable.DisconnectRequest\x1a\x1b.vstable.DisconnectResponse\x126\n" +
	"\x05Query\x12\x15.vstable.QueryRequest\x1a\x16.vstable.QueryResponse\x12H\n" +
	"\x12GenerateAlterTable\x12\x14.vstable.DiffRequest\x1a\x1c.vstable.GenerateSQLResponse\x12I\n" +
	"\x13GenerateCreateTable\x12\x14.vstable.DiffRequest\x1a\x1c.vstable.GenerateSQLResponseB\x1cZ\x1avstable-engine/internal/pbb\x06proto3"

var (
	file_api_vstable_proto_rawDescOnce sync.Once
	file_api_vstable_proto_rawDescData []byte
)

func file_api_vstable_proto_rawDescGZIP() []byte {
	file_api_vstable_proto_rawDescOnce.Do(func() {
		file_api_vstable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vstable_proto_rawDesc), len(file_api_vstable_proto_rawDesc)))
	})
	return file_api_vstable_proto_rawDescData
}

var file_api_vstable_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_vstable_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: vstable.PingRequest
	(*PingResponse)(nil),              // 1: vstable.PingResponse
	(*ConnectRequest)(nil),            // 2: vstable.ConnectRequest
	(*ConnectResponse)(nil),           // 3: vstable.ConnectResponse
	(*DisconnectRequest)(nil),         // 4: vstable.DisconnectRequest
	(*DisconnectResponse)(nil),        // 5: vstable.DisconnectResponse
	(*QueryRequest)(nil),              // 6: vstable.QueryRequest
	(*FieldInfo)(nil),                 // 7: vstable.FieldInfo
	(*QueryResponse)(nil),             // 8: vstable.QueryResponse
	(*ColumnDefinition)(nil),          // 9: vstable.ColumnDefinition
	(*IndexDefinition)(nil),           // 10: vstable.IndexDefinition
	(*ForeignKeyDefinition)(nil),      // 11: vstable.ForeignKeyDefinition
	(*CheckConstraintDefinition)(nil), // 12: vstable.CheckConstraintDefinition
	(*ViewDefinition)(nil),            // 13: vstable.ViewDefinition
	(*TriggerDefinition)(nil),         // 14: vstable.TriggerDefinition
	(*RoutineDefinition)(nil),         // 15: vstable.RoutineDefinition
	(*DatabaseConfig)(nil),            // 16: vstable.DatabaseConfig
	(*DiffRequest)(nil),               // 17: vstable.DiffRequest
	(*GenerateSQLResponse)(nil),       // 18: vstable.GenerateSQLResponse
	(*structpb.ListValue)(nil),        // 19: google.protobuf.ListValue
	(*structpb.Struct)(nil),           // 20: google.protobuf.Struct
}
var file_api_vstable_proto_depIdxs = []int32{
	19, // 0: vstable.QueryRequest.params:type_name -> google.protobuf.ListValue
	20, // 1: vstable.QueryResponse.rows:type_name -> google.protobuf.Struct
	7,  // 2: vstable.QueryResponse.fields:type_name -> vstable.FieldInfo
	9,  // 3: vstable.ColumnDefinition.original:type_name -> vstable.ColumnDefinition
	10, // 4: vstable.IndexDefinition.original:type_name -> vstable.IndexDefinition
	11, // 5: vstable.ForeignKeyDefinition.original:type_name -> vstable.ForeignKeyDefinition
	12, // 6: vstable.CheckConstraintDefinition.original:type_name -> vstable.CheckConstraintDefinition
	13, // 7: vstable.ViewDefinition.original:type_name -> vstable.ViewDefinition
	14, // 8: vstable.TriggerDefinition.original:type_name -> vstable.TriggerDefinition
	15, // 9: vstable.RoutineDefinition.original:type_name -> vstable.RoutineDefinition
	9,  // 10: vstable.DiffRequest.columns:type_name -> vstable.ColumnDefinition
	10, // 11: vstable.DiffRequest.indexes:type_name -> vstable.IndexDefinition
	9,  // 12: vstable.DiffRequest.deleted_columns:type_name -> vstable.ColumnDefinition
	10, // 13: vstable.DiffRequest.deleted_indexes:type_name -> vstable.IndexDefinition
	11, // 14: vstable.DiffRequest.foreign_keys:type_name -> vstable.ForeignKeyDefinition
	11, // 15: vstable.DiffRequest.deleted_foreign_keys:type_name -> vstable.ForeignKeyDefinition
	12, // 16: vstable.DiffRequest.check_constraints:type_name -> vstable.CheckConstraintDefinition
	12, // 17: vstable.DiffRequest.deleted_checks:type_name -> vstable.CheckConstraintDefinition
	13, // 18: vstable.DiffRequest.views:type_name -> vstable.ViewDefinition
	13, // 19: vstable.DiffRequest.deleted_views:type_name -> vstable.ViewDefinition
	14, // 20: vstable.DiffRequest.triggers:type_name -> vstable.TriggerDefinition
	14, // 21: vstable.DiffRequest.deleted_triggers:type_name -> vstable.TriggerDefinition
	15, // 22: vstable.DiffRequest.routines:type_name -> vstable.RoutineDefinition
	15, // 23: vstable.DiffRequest.deleted_routines:type_name -> vstable.RoutineDefinition
	16, // 24: vstable.DiffRequest.config:type_name -> vstable.DatabaseConfig
	0,  // 25: vstable.EngineService.Ping:input_type -> vstable.PingRequest
	2,  // 26: vstable.EngineService.DbConnect:input_type -> vstable.ConnectRequest
	4,  // 27: vstable.EngineService.Disconnect:input_type -> vstable.DisconnectRequest
	6,  // 28: vstable.EngineService.Query:input_type -> vstable.QueryRequest
	17, // 29: vstable.EngineService.GenerateAlterTable:input_type -> vstable.DiffRequest
	17, // 30: vstable.EngineService.GenerateCreateTable:input_type -> vstable.DiffRequest
	1,  // 31: vstable.EngineService.Ping:output_type -> vstable.PingResponse
	3,  // 32: vstable.EngineService.DbConnect:output_type -> vstable.ConnectResponse
	5,  // 33: vstable.EngineService.Disconnect:output_type -> vstable.DisconnectResponse
	8,  // 34: vstable.EngineService.Query:output_type -> vstable.QueryResponse
	18, // 35: vstable.EngineService.GenerateAlterTable:output_type -> vstable.GenerateSQLResponse
	18, // 36: vstable.EngineService.GenerateCreateTable:output_type -> vstable.GenerateSQLResponse
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_vstable_proto_init() }
func file_api_vstable_proto_init() {
	if File_api_vstable_proto != nil {
		return
	}
	file_api_vstable_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vstable_proto_rawDesc), len(file_api_vstable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vstable_proto_goTypes,
		DependencyIndexes: file_api_vstable_proto_depIdxs,
		MessageInfos:      file_api_vstable_proto_msgTypes,
	}.Build()
	File_api_vstable_proto = out.File
	file_api_vstable_proto_goTypes = nil
	file_api_vstable_proto_depIdxs = nil
}
