// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v7.34.0
// source: vstable.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';
import type { CallContext, CallOptions } from 'nice-grpc-common';
import { ListValue, Struct } from './google/protobuf/struct';

export const protobufPackage = 'vstable';

export type PingRequest = {};

export interface PingResponse {
  status?: string | undefined;
}

export interface ConnectRequest {
  id?: string | undefined;
  dialect?: string | undefined;
  dsn?: string | undefined;
}

export interface ConnectResponse {
  success?: boolean | undefined;
}

export interface DisconnectRequest {
  id?: string | undefined;
}

export interface DisconnectResponse {
  success?: boolean | undefined;
}

export interface QueryRequest {
  id?: string | undefined;
  sql?: string | undefined;
  params?: Array<any> | undefined;
}

export interface FieldInfo {
  name?: string | undefined;
  type?: string | undefined;
}

export interface QueryResponse {
  success?: boolean | undefined;
  rows?: { [key: string]: any }[] | undefined;
  fields?: FieldInfo[] | undefined;
}

export interface ColumnDefinition {
  id?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
  enumValues?: string[] | undefined;
  length?: number | undefined;
  precision?: number | undefined;
  scale?: number | undefined;
  nullable?: boolean | undefined;
  defaultValue?: string | undefined;
  isDefaultExpression?: boolean | undefined;
  isPrimaryKey?: boolean | undefined;
  isAutoIncrement?: boolean | undefined;
  isIdentity?: boolean | undefined;
  comment?: string | undefined;
  pkConstraintName?: string | undefined;
  originalIndex?: number | undefined;
  original?: ColumnDefinition | undefined;
}

export interface IndexDefinition {
  id?: string | undefined;
  name?: string | undefined;
  columns?: string[] | undefined;
  isUnique?: boolean | undefined;
  original?: IndexDefinition | undefined;
}

export interface ForeignKeyDefinition {
  id?: string | undefined;
  name?: string | undefined;
  columns?: string[] | undefined;
  referencedTable?: string | undefined;
  referencedColumns?: string[] | undefined;
  onDelete?: string | undefined;
  onUpdate?: string | undefined;
  original?: ForeignKeyDefinition | undefined;
}

export interface CheckConstraintDefinition {
  id?: string | undefined;
  name?: string | undefined;
  expression?: string | undefined;
  original?: CheckConstraintDefinition | undefined;
}

export interface ViewDefinition {
  id?: string | undefined;
  name?: string | undefined;
  definition?: string | undefined;
  original?: ViewDefinition | undefined;
}

export interface TriggerDefinition {
  id?: string | undefined;
  name?: string | undefined;
  timing?: string | undefined;
  event?: string | undefined;
  tableName?: string | undefined;
  definition?: string | undefined;
  enabled?: boolean | undefined;
  original?: TriggerDefinition | undefined;
}

export interface RoutineDefinition {
  id?: string | undefined;
  name?: string | undefined;
  type?: string | undefined;
  definition?: string | undefined;
  original?: RoutineDefinition | undefined;
}

export interface DatabaseConfig {
  charset?: string | undefined;
  collation?: string | undefined;
  engine?: string | undefined;
  autoIncrementOffset?: number | undefined;
}

export interface DiffRequest {
  dialect?: string | undefined;
  schema?: string | undefined;
  tableName?: string | undefined;
  oldTableName?: string | undefined;
  columns?: ColumnDefinition[] | undefined;
  indexes?: IndexDefinition[] | undefined;
  deletedColumns?: ColumnDefinition[] | undefined;
  deletedIndexes?: IndexDefinition[] | undefined;
  foreignKeys?: ForeignKeyDefinition[] | undefined;
  deletedForeignKeys?: ForeignKeyDefinition[] | undefined;
  checkConstraints?: CheckConstraintDefinition[] | undefined;
  deletedChecks?: CheckConstraintDefinition[] | undefined;
  views?: ViewDefinition[] | undefined;
  deletedViews?: ViewDefinition[] | undefined;
  triggers?: TriggerDefinition[] | undefined;
  deletedTriggers?: TriggerDefinition[] | undefined;
  routines?: RoutineDefinition[] | undefined;
  deletedRoutines?: RoutineDefinition[] | undefined;
  config?: DatabaseConfig | undefined;
}

export interface GenerateSQLResponse {
  success?: boolean | undefined;
  sqls?: string[] | undefined;
}

function createBasePingRequest(): PingRequest {
  return {};
}

export const PingRequest: MessageFns<PingRequest> = {
  encode(_: PingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePingResponse(): PingResponse {
  return { status: '' };
}

export const PingResponse: MessageFns<PingResponse> = {
  encode(message: PingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined && message.status !== '') {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConnectRequest(): ConnectRequest {
  return { id: '', dialect: '', dsn: '' };
}

export const ConnectRequest: MessageFns<ConnectRequest> = {
  encode(message: ConnectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.dialect !== undefined && message.dialect !== '') {
      writer.uint32(18).string(message.dialect);
    }
    if (message.dsn !== undefined && message.dsn !== '') {
      writer.uint32(26).string(message.dsn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dialect = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dsn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseConnectResponse(): ConnectResponse {
  return { success: false };
}

export const ConnectResponse: MessageFns<ConnectResponse> = {
  encode(message: ConnectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined && message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDisconnectRequest(): DisconnectRequest {
  return { id: '' };
}

export const DisconnectRequest: MessageFns<DisconnectRequest> = {
  encode(message: DisconnectRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisconnectRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisconnectRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDisconnectResponse(): DisconnectResponse {
  return { success: false };
}

export const DisconnectResponse: MessageFns<DisconnectResponse> = {
  encode(message: DisconnectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined && message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DisconnectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDisconnectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseQueryRequest(): QueryRequest {
  return { id: '', sql: '', params: undefined };
}

export const QueryRequest: MessageFns<QueryRequest> = {
  encode(message: QueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.sql !== undefined && message.sql !== '') {
      writer.uint32(18).string(message.sql);
    }
    if (message.params !== undefined) {
      ListValue.encode(ListValue.wrap(message.params), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sql = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.params = ListValue.unwrap(ListValue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseFieldInfo(): FieldInfo {
  return { name: '', type: '' };
}

export const FieldInfo: MessageFns<FieldInfo> = {
  encode(message: FieldInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== undefined && message.type !== '') {
      writer.uint32(18).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseQueryResponse(): QueryResponse {
  return { success: false, rows: [], fields: [] };
}

export const QueryResponse: MessageFns<QueryResponse> = {
  encode(message: QueryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined && message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.rows !== undefined && message.rows.length !== 0) {
      for (const v of message.rows) {
        Struct.encode(Struct.wrap(v!), writer.uint32(18).fork()).join();
      }
    }
    if (message.fields !== undefined && message.fields.length !== 0) {
      for (const v of message.fields) {
        FieldInfo.encode(v!, writer.uint32(26).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const el = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          if (el !== undefined) {
            message.rows!.push(el);
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = FieldInfo.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.fields!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseColumnDefinition(): ColumnDefinition {
  return {
    id: '',
    name: '',
    type: '',
    enumValues: [],
    length: undefined,
    precision: undefined,
    scale: undefined,
    nullable: false,
    defaultValue: undefined,
    isDefaultExpression: false,
    isPrimaryKey: false,
    isAutoIncrement: false,
    isIdentity: false,
    comment: '',
    pkConstraintName: '',
    originalIndex: 0,
    original: undefined,
  };
}

export const ColumnDefinition: MessageFns<ColumnDefinition> = {
  encode(message: ColumnDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== undefined && message.type !== '') {
      writer.uint32(26).string(message.type);
    }
    if (message.enumValues !== undefined && message.enumValues.length !== 0) {
      for (const v of message.enumValues) {
        writer.uint32(34).string(v!);
      }
    }
    if (message.length !== undefined) {
      writer.uint32(40).int64(message.length);
    }
    if (message.precision !== undefined) {
      writer.uint32(48).int64(message.precision);
    }
    if (message.scale !== undefined) {
      writer.uint32(56).int64(message.scale);
    }
    if (message.nullable !== undefined && message.nullable !== false) {
      writer.uint32(64).bool(message.nullable);
    }
    if (message.defaultValue !== undefined) {
      writer.uint32(74).string(message.defaultValue);
    }
    if (message.isDefaultExpression !== undefined && message.isDefaultExpression !== false) {
      writer.uint32(80).bool(message.isDefaultExpression);
    }
    if (message.isPrimaryKey !== undefined && message.isPrimaryKey !== false) {
      writer.uint32(88).bool(message.isPrimaryKey);
    }
    if (message.isAutoIncrement !== undefined && message.isAutoIncrement !== false) {
      writer.uint32(96).bool(message.isAutoIncrement);
    }
    if (message.isIdentity !== undefined && message.isIdentity !== false) {
      writer.uint32(104).bool(message.isIdentity);
    }
    if (message.comment !== undefined && message.comment !== '') {
      writer.uint32(114).string(message.comment);
    }
    if (message.pkConstraintName !== undefined && message.pkConstraintName !== '') {
      writer.uint32(122).string(message.pkConstraintName);
    }
    if (message.originalIndex !== undefined && message.originalIndex !== 0) {
      writer.uint32(128).int32(message.originalIndex);
    }
    if (message.original !== undefined) {
      ColumnDefinition.encode(message.original, writer.uint32(138).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ColumnDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseColumnDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.enumValues!.push(el);
          }
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.length = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.precision = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.scale = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.nullable = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.defaultValue = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.isDefaultExpression = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isPrimaryKey = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.isAutoIncrement = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.isIdentity = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.comment = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.pkConstraintName = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.originalIndex = reader.int32();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.original = ColumnDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseIndexDefinition(): IndexDefinition {
  return { id: '', name: '', columns: [], isUnique: false, original: undefined };
}

export const IndexDefinition: MessageFns<IndexDefinition> = {
  encode(message: IndexDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.columns !== undefined && message.columns.length !== 0) {
      for (const v of message.columns) {
        writer.uint32(26).string(v!);
      }
    }
    if (message.isUnique !== undefined && message.isUnique !== false) {
      writer.uint32(32).bool(message.isUnique);
    }
    if (message.original !== undefined) {
      IndexDefinition.encode(message.original, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IndexDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIndexDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.columns!.push(el);
          }
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isUnique = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.original = IndexDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseForeignKeyDefinition(): ForeignKeyDefinition {
  return {
    id: '',
    name: '',
    columns: [],
    referencedTable: '',
    referencedColumns: [],
    onDelete: '',
    onUpdate: '',
    original: undefined,
  };
}

export const ForeignKeyDefinition: MessageFns<ForeignKeyDefinition> = {
  encode(message: ForeignKeyDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.columns !== undefined && message.columns.length !== 0) {
      for (const v of message.columns) {
        writer.uint32(26).string(v!);
      }
    }
    if (message.referencedTable !== undefined && message.referencedTable !== '') {
      writer.uint32(34).string(message.referencedTable);
    }
    if (message.referencedColumns !== undefined && message.referencedColumns.length !== 0) {
      for (const v of message.referencedColumns) {
        writer.uint32(42).string(v!);
      }
    }
    if (message.onDelete !== undefined && message.onDelete !== '') {
      writer.uint32(50).string(message.onDelete);
    }
    if (message.onUpdate !== undefined && message.onUpdate !== '') {
      writer.uint32(58).string(message.onUpdate);
    }
    if (message.original !== undefined) {
      ForeignKeyDefinition.encode(message.original, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ForeignKeyDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseForeignKeyDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.columns!.push(el);
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.referencedTable = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.referencedColumns!.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.onDelete = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.onUpdate = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.original = ForeignKeyDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckConstraintDefinition(): CheckConstraintDefinition {
  return { id: '', name: '', expression: '', original: undefined };
}

export const CheckConstraintDefinition: MessageFns<CheckConstraintDefinition> = {
  encode(
    message: CheckConstraintDefinition,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.expression !== undefined && message.expression !== '') {
      writer.uint32(26).string(message.expression);
    }
    if (message.original !== undefined) {
      CheckConstraintDefinition.encode(message.original, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckConstraintDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckConstraintDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.expression = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.original = CheckConstraintDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseViewDefinition(): ViewDefinition {
  return { id: '', name: '', definition: '', original: undefined };
}

export const ViewDefinition: MessageFns<ViewDefinition> = {
  encode(message: ViewDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.definition !== undefined && message.definition !== '') {
      writer.uint32(26).string(message.definition);
    }
    if (message.original !== undefined) {
      ViewDefinition.encode(message.original, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ViewDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseViewDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.definition = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.original = ViewDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseTriggerDefinition(): TriggerDefinition {
  return {
    id: '',
    name: '',
    timing: '',
    event: '',
    tableName: '',
    definition: '',
    enabled: false,
    original: undefined,
  };
}

export const TriggerDefinition: MessageFns<TriggerDefinition> = {
  encode(message: TriggerDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.timing !== undefined && message.timing !== '') {
      writer.uint32(26).string(message.timing);
    }
    if (message.event !== undefined && message.event !== '') {
      writer.uint32(34).string(message.event);
    }
    if (message.tableName !== undefined && message.tableName !== '') {
      writer.uint32(42).string(message.tableName);
    }
    if (message.definition !== undefined && message.definition !== '') {
      writer.uint32(50).string(message.definition);
    }
    if (message.enabled !== undefined && message.enabled !== false) {
      writer.uint32(56).bool(message.enabled);
    }
    if (message.original !== undefined) {
      TriggerDefinition.encode(message.original, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.timing = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tableName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.definition = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.original = TriggerDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRoutineDefinition(): RoutineDefinition {
  return { id: '', name: '', type: '', definition: '', original: undefined };
}

export const RoutineDefinition: MessageFns<RoutineDefinition> = {
  encode(message: RoutineDefinition, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== '') {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== undefined && message.name !== '') {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== undefined && message.type !== '') {
      writer.uint32(26).string(message.type);
    }
    if (message.definition !== undefined && message.definition !== '') {
      writer.uint32(34).string(message.definition);
    }
    if (message.original !== undefined) {
      RoutineDefinition.encode(message.original, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RoutineDefinition {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRoutineDefinition();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.definition = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.original = RoutineDefinition.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDatabaseConfig(): DatabaseConfig {
  return { charset: '', collation: '', engine: '', autoIncrementOffset: 0 };
}

export const DatabaseConfig: MessageFns<DatabaseConfig> = {
  encode(message: DatabaseConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.charset !== undefined && message.charset !== '') {
      writer.uint32(10).string(message.charset);
    }
    if (message.collation !== undefined && message.collation !== '') {
      writer.uint32(18).string(message.collation);
    }
    if (message.engine !== undefined && message.engine !== '') {
      writer.uint32(26).string(message.engine);
    }
    if (message.autoIncrementOffset !== undefined && message.autoIncrementOffset !== 0) {
      writer.uint32(32).int32(message.autoIncrementOffset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DatabaseConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDatabaseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.charset = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.collation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.engine = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.autoIncrementOffset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDiffRequest(): DiffRequest {
  return {
    dialect: '',
    schema: '',
    tableName: '',
    oldTableName: '',
    columns: [],
    indexes: [],
    deletedColumns: [],
    deletedIndexes: [],
    foreignKeys: [],
    deletedForeignKeys: [],
    checkConstraints: [],
    deletedChecks: [],
    views: [],
    deletedViews: [],
    triggers: [],
    deletedTriggers: [],
    routines: [],
    deletedRoutines: [],
    config: undefined,
  };
}

export const DiffRequest: MessageFns<DiffRequest> = {
  encode(message: DiffRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dialect !== undefined && message.dialect !== '') {
      writer.uint32(10).string(message.dialect);
    }
    if (message.schema !== undefined && message.schema !== '') {
      writer.uint32(18).string(message.schema);
    }
    if (message.tableName !== undefined && message.tableName !== '') {
      writer.uint32(26).string(message.tableName);
    }
    if (message.oldTableName !== undefined && message.oldTableName !== '') {
      writer.uint32(34).string(message.oldTableName);
    }
    if (message.columns !== undefined && message.columns.length !== 0) {
      for (const v of message.columns) {
        ColumnDefinition.encode(v!, writer.uint32(42).fork()).join();
      }
    }
    if (message.indexes !== undefined && message.indexes.length !== 0) {
      for (const v of message.indexes) {
        IndexDefinition.encode(v!, writer.uint32(50).fork()).join();
      }
    }
    if (message.deletedColumns !== undefined && message.deletedColumns.length !== 0) {
      for (const v of message.deletedColumns) {
        ColumnDefinition.encode(v!, writer.uint32(58).fork()).join();
      }
    }
    if (message.deletedIndexes !== undefined && message.deletedIndexes.length !== 0) {
      for (const v of message.deletedIndexes) {
        IndexDefinition.encode(v!, writer.uint32(66).fork()).join();
      }
    }
    if (message.foreignKeys !== undefined && message.foreignKeys.length !== 0) {
      for (const v of message.foreignKeys) {
        ForeignKeyDefinition.encode(v!, writer.uint32(74).fork()).join();
      }
    }
    if (message.deletedForeignKeys !== undefined && message.deletedForeignKeys.length !== 0) {
      for (const v of message.deletedForeignKeys) {
        ForeignKeyDefinition.encode(v!, writer.uint32(82).fork()).join();
      }
    }
    if (message.checkConstraints !== undefined && message.checkConstraints.length !== 0) {
      for (const v of message.checkConstraints) {
        CheckConstraintDefinition.encode(v!, writer.uint32(90).fork()).join();
      }
    }
    if (message.deletedChecks !== undefined && message.deletedChecks.length !== 0) {
      for (const v of message.deletedChecks) {
        CheckConstraintDefinition.encode(v!, writer.uint32(98).fork()).join();
      }
    }
    if (message.views !== undefined && message.views.length !== 0) {
      for (const v of message.views) {
        ViewDefinition.encode(v!, writer.uint32(106).fork()).join();
      }
    }
    if (message.deletedViews !== undefined && message.deletedViews.length !== 0) {
      for (const v of message.deletedViews) {
        ViewDefinition.encode(v!, writer.uint32(114).fork()).join();
      }
    }
    if (message.triggers !== undefined && message.triggers.length !== 0) {
      for (const v of message.triggers) {
        TriggerDefinition.encode(v!, writer.uint32(122).fork()).join();
      }
    }
    if (message.deletedTriggers !== undefined && message.deletedTriggers.length !== 0) {
      for (const v of message.deletedTriggers) {
        TriggerDefinition.encode(v!, writer.uint32(130).fork()).join();
      }
    }
    if (message.routines !== undefined && message.routines.length !== 0) {
      for (const v of message.routines) {
        RoutineDefinition.encode(v!, writer.uint32(138).fork()).join();
      }
    }
    if (message.deletedRoutines !== undefined && message.deletedRoutines.length !== 0) {
      for (const v of message.deletedRoutines) {
        RoutineDefinition.encode(v!, writer.uint32(146).fork()).join();
      }
    }
    if (message.config !== undefined) {
      DatabaseConfig.encode(message.config, writer.uint32(154).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DiffRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDiffRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.dialect = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.schema = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tableName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.oldTableName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = ColumnDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.columns!.push(el);
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const el = IndexDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.indexes!.push(el);
          }
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const el = ColumnDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedColumns!.push(el);
          }
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          const el = IndexDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedIndexes!.push(el);
          }
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const el = ForeignKeyDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.foreignKeys!.push(el);
          }
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          const el = ForeignKeyDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedForeignKeys!.push(el);
          }
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          const el = CheckConstraintDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.checkConstraints!.push(el);
          }
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          const el = CheckConstraintDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedChecks!.push(el);
          }
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          const el = ViewDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.views!.push(el);
          }
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          const el = ViewDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedViews!.push(el);
          }
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          const el = TriggerDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.triggers!.push(el);
          }
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          const el = TriggerDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedTriggers!.push(el);
          }
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          const el = RoutineDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.routines!.push(el);
          }
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          const el = RoutineDefinition.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.deletedRoutines!.push(el);
          }
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.config = DatabaseConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGenerateSQLResponse(): GenerateSQLResponse {
  return { success: false, sqls: [] };
}

export const GenerateSQLResponse: MessageFns<GenerateSQLResponse> = {
  encode(message: GenerateSQLResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== undefined && message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.sqls !== undefined && message.sqls.length !== 0) {
      for (const v of message.sqls) {
        writer.uint32(18).string(v!);
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateSQLResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateSQLResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const el = reader.string();
          if (el !== undefined) {
            message.sqls!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export type EngineServiceDefinition = typeof EngineServiceDefinition;
export const EngineServiceDefinition = {
  name: 'EngineService',
  fullName: 'vstable.EngineService',
  methods: {
    ping: {
      name: 'Ping',
      requestType: PingRequest as typeof PingRequest,
      requestStream: false,
      responseType: PingResponse as typeof PingResponse,
      responseStream: false,
      options: {},
    },
    dbConnect: {
      name: 'DbConnect',
      requestType: ConnectRequest as typeof ConnectRequest,
      requestStream: false,
      responseType: ConnectResponse as typeof ConnectResponse,
      responseStream: false,
      options: {},
    },
    disconnect: {
      name: 'Disconnect',
      requestType: DisconnectRequest as typeof DisconnectRequest,
      requestStream: false,
      responseType: DisconnectResponse as typeof DisconnectResponse,
      responseStream: false,
      options: {},
    },
    query: {
      name: 'Query',
      requestType: QueryRequest as typeof QueryRequest,
      requestStream: false,
      responseType: QueryResponse as typeof QueryResponse,
      responseStream: false,
      options: {},
    },
    generateAlterTable: {
      name: 'GenerateAlterTable',
      requestType: DiffRequest as typeof DiffRequest,
      requestStream: false,
      responseType: GenerateSQLResponse as typeof GenerateSQLResponse,
      responseStream: false,
      options: {},
    },
    generateCreateTable: {
      name: 'GenerateCreateTable',
      requestType: DiffRequest as typeof DiffRequest,
      requestStream: false,
      responseType: GenerateSQLResponse as typeof GenerateSQLResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface EngineServiceImplementation<CallContextExt = {}> {
  ping(request: PingRequest, context: CallContext & CallContextExt): Promise<PingResponse>;
  dbConnect(
    request: ConnectRequest,
    context: CallContext & CallContextExt
  ): Promise<ConnectResponse>;
  disconnect(
    request: DisconnectRequest,
    context: CallContext & CallContextExt
  ): Promise<DisconnectResponse>;
  query(request: QueryRequest, context: CallContext & CallContextExt): Promise<QueryResponse>;
  generateAlterTable(
    request: DiffRequest,
    context: CallContext & CallContextExt
  ): Promise<GenerateSQLResponse>;
  generateCreateTable(
    request: DiffRequest,
    context: CallContext & CallContextExt
  ): Promise<GenerateSQLResponse>;
}

export interface EngineServiceClient<CallOptionsExt = {}> {
  ping(request: PingRequest, options?: CallOptions & CallOptionsExt): Promise<PingResponse>;
  dbConnect(
    request: ConnectRequest,
    options?: CallOptions & CallOptionsExt
  ): Promise<ConnectResponse>;
  disconnect(
    request: DisconnectRequest,
    options?: CallOptions & CallOptionsExt
  ): Promise<DisconnectResponse>;
  query(request: QueryRequest, options?: CallOptions & CallOptionsExt): Promise<QueryResponse>;
  generateAlterTable(
    request: DiffRequest,
    options?: CallOptions & CallOptionsExt
  ): Promise<GenerateSQLResponse>;
  generateCreateTable(
    request: DiffRequest,
    options?: CallOptions & CallOptionsExt
  ): Promise<GenerateSQLResponse>;
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error('Value is larger than Number.MAX_SAFE_INTEGER');
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error('Value is smaller than Number.MIN_SAFE_INTEGER');
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
